// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzeftrimeekcuxhdxzge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZWZ0cmltZWVrY3V4aGR4emdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTA0NzcsImV4cCI6MjA3MDA4NjQ3N30.QqqW5c-Qu1jQo9-1UJ5nNifSwNk-bbtmtSZ6Kmaay-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});